services:
  app:
    build:
      context: docker
    ports:
      - 3000:3000
    volumes:
      - ./nuxt:/niwatori-no-kimochi:cached
      - node_modules:/niwatori-no-kimochi/node_modules
    working_dir: "/niwatori-no-kimochi"
    tty: true
    environment:
      - HOST=0.0.0.0
      - port=3000
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "yarn && yarn dev -o"
volumes:
  node_modules:
